<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>volmethin-cli</AssemblyName>
    <RootNamespace>VolmeThin.Builder</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\VolmeThin.Core\VolmeThin.Core.csproj" />
    <ProjectReference Include="..\VolmeThin.Capture\VolmeThin.Capture.csproj" />
  </ItemGroup>
</Project>
