<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>VolmeThin</AssemblyName>
    <RootNamespace>VolmeThin.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\VolmeThin.Core\VolmeThin.Core.csproj" />
    <ProjectReference Include="..\VolmeThin.Capture\VolmeThin.Capture.csproj" />
    <ProjectReference Include="..\VolmeThin.Builder\VolmeThin.Builder.csproj" />
  </ItemGroup>
</Project>
